import { Button, VerticalBox, ScrollView, HorizontalBox } from "std-widgets.slint";
import { displayImages } from "displayimages.slint";
import { SideBar } from "sidebar.slint";


export component AppWindow inherits Window {
    title: @tr("Bilinear Interpolation");

    preferred-height: 300px;
    preferred-width: 300px;

    callback clicked();
    in property<image> selected_image: @image-url("");
    in property <bool> valid_image_selected;
    property <image> emptyImage: @image-url("");

    // VerticalBox {
    //     // max-width: 400px;
    //     Button {
    //         // max-width: 30px;
    //         primary: true;
    //         text: "Open Image";
    //         clicked => {
    //             root.clicked();
    //         }
    //     }

    //     Text {
    //         // text: selected_image;
    //         // width: 300px;
    //     }
        
    //     Rectangle {
            
    //         border-radius: 5px;
            
    //     }

    //     GridLayout {
    //         preferred-height: 300px;
    //         preferred-width: 300px;
    //         Rectangle {
    //             background: red;
    //             preferred-height: 80px;
    //             preferred-width: 80px;
    //         }

    //         Rectangle {
    //             background: green;
    //             preferred-height: 80px;
    //             preferred-width: 80px;
    //         }

    //         Rectangle {
    //             background: yellow;
    //             preferred-height: 80px;
    //             preferred-width: 80px;
    //             max-width: 100px;
    //         }
    //     }

    //     ScrollView {
    //         enabled: true;
    //         viewport-height: 600px;
    //         viewport-width: 500px;
        
    //         Image {
    //             // source: @image-url("{root.selected_image}");
    //             source: selected_image;
    //             image-fit: contain;
                
                
    //         }
    //     }
        
    // }

    HorizontalBox {
        padding: 0px;
        VerticalBox {
            inputImage := displayImages {
                // bgcolor: red;
                isPrimaryDisplay: true;

                inputimage: selected_image;
                select_action => {root.clicked();}
            }

            Button {
                preferred-width: 120px;
                primary: true;
                text: "Open Image";
                clicked => {
                root.clicked();
                }
            }
        }
        

        outputImage := displayImages {
            // bgcolor: blue;
        }


        SideBar {
            ValidImageLoaded: valid_image_selected;
        }

        

    }


}

