import { Button, VerticalBox } from "std-widgets.slint";


export component AppWindow inherits Window {

    preferred-height: 300px;
    preferred-width: 300px;
    callback clicked();
    in property<image> selected_image: @image-url("");

    VerticalBox {
        Button {
            text: "Open Image";
            clicked => {
                root.clicked();
            }
        }

        Text {
            // text: selected_image;
        }
        Image {
            // source: @image-url("{root.selected_image}");
            source: selected_image;
        }
    }
}

