import { ScrollView, Spinner, Button } from "std-widgets.slint";
export component displayImages inherits Rectangle {

    in property <color> bgcolor;
    in property <image> inputimage;
    in property <bool> isPrimaryDisplay;
    callback select_action();

    min-width: 400px;
    min-height: 400px;

    preferred-height: 500px;
    preferred-width: 500px;

    // max-height: 600px;
    // max-width: 600px;

    background: bgcolor;

    ScrollView {
        enabled: true;
        viewport-height: inputimage.height * 1px;
        viewport-width: inputimage.width * 1px;

        if (inputimage.height == 0): Rectangle {

            x: root.width / 2;
            y: root.height / 2;
            
            if isPrimaryDisplay: Rectangle {
                Button {
                    text: @tr("Select Image");
                    clicked => {select_action();}
                }
            }

            if !isPrimaryDisplay: Rectangle {
                Text {
                    text: @tr("Output will be displayed here");
                }
            }

            
            
        }

        Image {
            source: inputimage;
            image-fit: contain;
        }
    }
}